version: '3.8'

name: transcendence

services:
  backend:
    container_name: backend
    image: backend-img
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - media_data:/app/user/profile_images
    networks:
      - app-network
    depends_on:
      - db
    env_file:
      - ./backend/.env
    init: true

  frontend:
    container_name: frontend
    image: frontend-img
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network
    init: true

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - media_data:/app/user/profile_images
    networks:
      - app-network
    init: true

  db:
    build: ./db
    networks:
      - app-network
    env_file:
      - ./backend/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U Newjeans" ]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    init: true


networks:
  app-network:
    driver: bridge

volumes:
  media_data:
  pgdata: